# fwcteam <fwcteam.github.io>
VERSION="2.2.0"
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GAUXLLKKZEUAMHSNEYIH7SJYSAIDIPATE7HEBVJRONYS2WL4SZJ62ETI"
]

[DOCUMENTATION]
ORG_NAME="fwcteam"
ORG_URL="https://fwcteam.github.io"
ORG_LOGO = "https://fwcteam.github.io/img/fwc.png"
ORG_OFFICIAL_EMAIL="fwcteam@yahoo.com"
ORG_SUPPORT_EMAIL="fwcteam@yahoo.com"
ORG_TWITTER="0xfwcteam"
ORG_DESCRIPTION="fwcteam: Create Value to NFT Space"

[[PRINCIPALS]]
email="fwcteam@yahoo.com"

[[CURRENCIES]]
code = "FWC"
name = "FWC"
issuer = "GAUXLLKKZEUAMHSNEYIH7SJYSAIDIPATE7HEBVJRONYS2WL4SZJ62ETI"
is_asset_anchored=false
display_decimals = 7
desc="This is token of FWC."
image="https://fwcteam.github.io/img/fwc.png"
conditions="There will only ever be 1 billion FWC tokens in existence."
status="live"
anchor_asset_type="other"
fixed_number=1000000000
